site_name: My Docs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true          
  - toc:
      permalink: true          
  - tables

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: qfpay
site_name: QF Pay Docs
base_url: '/'

theme:
  name: material
  font:
    text: Consolas
    size: 14px
  # custom_dir: !ENV [THEME_DIR, "material"]
  logo: assets/logo.png
  palette: 
    # - primary: indigo
    # - primary: blue
    # - accent: blue
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode  
  features:
    - navigation.instant
   
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - navigation.top
    
    - toc.follow
    - toc.integrate
    
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  
nav:
    - Home: 'index.md'
    - 'Integration':
        - 'integration/payment.md'
        - 'integration/alipay service window h5.md'
        - 'integration/Transaction Enquiry.md'
    - 'Checkout Page': 'https://google.com'
    - 'Android SDK': 'https://google.com'

