name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: printenv
      # - run: echo $env:GITHUB_HEAD_REF_NAME
      # - run: echo ${{github.HEAD_REF_NAME}}
      # ref: https://stackoverflow.com/questions/60300169/how-to-get-branch-name-on-github-action
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF_NAME}
      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          stack: 'container'
          branch: 'staging'